var processor = new Generator("processor", "geometric")
var autotoaster = new Generator("autotoaster", "arithmetic")
var autotoasterspeed = new Generator("autotoaster.speed", "geometric")
var megatoaster = new Generator("megatoaster", "arithmetic")
var megatoasterpeed = new Generator("megatoaster.speed", "geometric")

sequence.init()
events.init()
control.init()
theme.init()
readout.init()
tick.init()
