sequence.init()
cost.init()
events.init()
control.init()
readout.init()
theme.init()
tick.init()
var processor = new Generator("processor", "geometric")
var autotoaster = new Generator("autotoaster", "arithmetic")
var autotoasterspeed = new Generator("autotoaster.speed", "geometric")
